#!/usr/bin/env python

import sys
import os
from os import path

lucas_ilm = "/lucas/ilm"
ilm_prefix = "/dept/rnd/home/cary/"
ilm_prefix = "/dept/rnd/home/cary/"
ilm_build = "/dept/rnd/builds/cary"

home_prefix = "/home/cary/"
home_build = "/home/cary/builds"

PYILMBASE_ENABLE = 0

SRC_DIR = os.getcwd()

if SRC_DIR.startswith (lucas_ilm):
    SRC_DIR = SRC_DIR[len(lucas_ilm):]

if SRC_DIR.startswith (ilm_prefix):

    project = SRC_DIR[len(ilm_prefix):]
    build = "%s/%s/cmake" % (ilm_build, project)
    if not path.exists (build):
        os.makedirs (build)

    CXX = "/opt/rh/devtoolset-6/root/bin/g++"
    C = "/opt/rh/devtoolset-6/root/bin/gcc"

elif SRC_DIR.startswith (home_prefix):

    project = SRC_DIR[len(home_prefix):]
    build = "%s/%s/cmake" % (home_build, project)
    if not path.exists (build):
        os.makedirs (build)

    CXX = "g++"
    C = "gcc"

print build
os.chdir (build)

if len (sys.argv) == 1:
    os.exit(0)

if sys.argv[1] == "cmake":

    cmd = "cmake %s " % SRC_DIR
    cmd += "-DCMAKE_INSTALL_PREFIX=%s " % build
    cmd += "-DCMAKE_SYSTEM_PREFIX=%s " % build
    cmd += "-DCMAKE_CXX_COMPILER=%s " % CXX
    cmd += "-DCMAKE_C_COMPILER=%s " % C
    cmd += "-DPYILMBASE_ENABLE=%s " % PYILMBASE_ENABLE

    print cmd
    os.system (cmd)

else:
    cmd = " ".join(sys.argv[1:])
    print "cmd: %s" % cmd
    os.system (cmd)
        
